### PR TITLE
Add JSON mode to Loki client

### PR DESCRIPTION
**Pull request by juliusrickert**
I experienced problems with newlines in the text-based logging. This motivated me to add a simple JSON mode to the Loki client.

### CODE REVIEW

**Comment by dmachard** [comment]
Thanks for this PR.
Can you share some details regarding your issue with newlines ?

**Comment by juliusrickert** [comment]
Je vous en prie !
Thank you for developing and providing this piece of software.

First, a minor issue: the log lines end in `\n`, requiring the `pattern` to match it to end in `\n`.

But furthermore, I'm seeing domain names starting in "-n " (including the space), having newlines in them, etc. This is breaking my Loki `pattern`.
I'm not sure what the origin of this behaviour is (yet).

In general, I think it's dangerous to use client-provided data without escaping it (:eyes: Log4Shell). Thus, I think a JSON-based logger for Loki is beneficial.

**Comment by dmachard** [comment]
Could you share an example of a full line?
I haven't observed any issues on my side with text mode

**Comment by juliusrickert** [comment]
I think I can share a redacted example, but on Monday at the earliest, as I don't have access from my personal computer.

But I think that's kind of unrelated to adding this feature. What do you think about merging it?

**Comment by dmachard** [comment]
I just want to understand what happened in your case and why I haven't observed that in my side.

**Comment by juliusrickert** [comment]
No problem. Thank you for merging.

I'll open an issue about this if I have any news.

**Comment by dmachard** [comment]
Thank, You can also open a [discussion ](https://github.com/dmachard/dns-collector/discussions) regarding Loki with the DNS-Collector; it will be great to share implementation.

**Pull request merged**
