### PR TITLE
Add support for Public Suffix

### PR DESCRIPTION
**Pull request by juliusrickert**
Add fields based on the public suffix list (PSL):

- public suffix
- public suffix + 1 label

Useful for aggregation.

### CODE REVIEW

**Comment by juliusrickert** [comment]
@dmachard What do you think about this?

I am mostly interested in aggregating by domain, so by public suffix + 1 label. (I know, there are cases for which this does not work.)

**Comment by dmachard** [comment]
Thank again, any PR will be apreciated.

Just  to be sure, have you take a look to the [User  feature privacy](https://github.com/dmachard/dns-collector/blob/main/doc/configuration.md#user-privacy) ? 

If my understand is correct, you can have acheived what you need by enable the `minimaze-name`
for example xx.mail.google.com wil be replaced by google.com so on the top domain metrics you have only tld+1label 

```
subprocessors:
  user-privacy:
    minimaze-qname: true
```

On another hand, your implemention is perphap better, have you make some bench regarding the publicsuffix library ?

**Comment by juliusrickert** [comment]
I did look at the user privacy feature but it doesn't work as intended for domains like .co.uk.

I have not conducted a performance test yet but I'm pretty certain that the impact would be negligible.

**Comment by dmachard** [comment]
> I did look at the user privacy feature but it doesn't work as intended for domains like .co.uk.

You're right, the qname minimization implementation is very basic.

Thanks for feedback regarding performance.

**Comment by dmachard** [comment]
Before to validate the merge request, could you add some [documentations](https://github.com/dmachard/dns-collector/blob/main/doc/configuration.md#custom-text-format) regarding the new directives `qnamepublicsuffix` and `qnameeffectivetldplusone` ?

Thanks again :)

**Comment by juliusrickert** [comment]
Hey @dmachard, I've added documentation regarding the newly added directives :)

**Pull request merged**
